name: Nightly build Ubuntu

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: nttld/setup-ndk@v1
      with:
        ndk-version: r21e
    - name: install_dependencies
      run: |
        curl -L -O https://github.com/pelya/commandergenius/archive/refs/heads/sdl_android.zip
        unzip sdl_android.zip
      env:
        ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

    - name: setup
      run: |
        cd commandergenius-sdl_android
        ./build.sh simutrans
      env:
        ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        

    - name: make
      run: make

    - name: distribute
      run: sh ./distribute.sh

    - name: Rename result
      run:  mv simu*.zip simulinux-x64-nightly.zip

    - name: Update binaries of Nightly Release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./simulinux-x64-nightly.zip
        asset_name: simulinux-x64-nightly.zip
        tag: Nightly
        overwrite: true

